const ROUTE_ERROR_CODES = {
  // Route
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
};

const USER_ERROR_CODES = {
  // User
  USER_EMAIL_DUPLICATED: "USER_EMAIL_DUPLICATED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
};

const SYSTEM_ERROR_CODES = {
  // System
  TECH_DATABASE_ERROR: "TECH_DATABASE_ERROR",
  TECH_INTERNAL_ERROR: "TECH_INTERNAL_ERROR",
};

export const ERROR_CODES = {
  ...ROUTE_ERROR_CODES,
  ...USER_ERROR_CODES,

  // System
  TECH_DATABASE_ERROR: "TECH_DATABASE_ERROR",
  TECH_INTERNAL_ERROR: "TECH_INTERNAL_ERROR",

  // Route
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
